const actionTypes = {
    SET_USER_HAND: 'SET_USER_HAND',
    SET_COMP_HAND: 'SET_COMP_HAND',
    SET_RESULT: 'SET_RESULT',
    SET_SCORE: 'SET_SCORE',
    INCREMENT_SCORE: 'INCREMENT_SCORE',
    DECREMENT_SCORE: 'DECREMENT_SCORE',
    RESET: 'RESET',
};

export default actionTypes;
